### ISSUE TITLE
Uses r modifier on y// but claiming 5.10 support

### ISSUE THREAD

**Issue by jwrightecs** [yanick/JSON-Schema-AsType#13]
r modifier on y// is not available in perl 5.10, and this module claims support for 5.10

`syntax error at /root/.cpanm/work/1491574504.63776/JSON-Schema-AsType-0.4.0/blib/lib/JSON/Schema/AsType.pm line 122, near "y#/#/#sr "
`

**Comment by yanick** [comment]
oops. Good catch. Thanks!
