### ISSUE TITLE
Use 'zip' from List::MoreUtils or from List::AllUtils ?

### ISSUE THREAD

**Issue by uniejo** [yanick/JSON-Schema-AsType#18]
I get the following error

Prototype mismatch: sub JSON::Schema::AsType::Draft4::Types::zip (\@\@;\@\@\@\@\@\@\@\@\@\@\@\@\@\@\@\@\@\@\@\@\@\@\@\@\@\@\@\@\@\@) vs none at /usr/lib/x86_64-linux-gnu/perl-base/Exporter.pm line 63.
 at xxxxx/t/../local/lib/perl5/JSON/Schema/AsType/Draft4/Types.pm line 108.
 
 In JSON::Schema::AsType::Draft4::Types i can see that 'zip' is inherited from two different places:
 
 use List::MoreUtils qw/ all any zip none /;

and further down

use List::AllUtils qw/ zip none uniq /;

The error goes away, if I replace the last line with

use List::AllUtils qw/ none uniq /;

**Comment by yanick** [comment]
Good catch. Fixed and on its way to CPAN!
