### ISSUE TITLE
Handle nested allOf / anyOf

### ISSUE THREAD

**Issue by dnmfarrell** [yanick/JSON-Schema-AsType#4]
Cool module! I ran into some trouble parsing a [json schema](https://github.com/dnmfarrell/Settlers-Game-Notation/blob/master/schema/message.json) I'm working on. I could be wrong, but JSON::Schema::AsType appears to apply the surrounding `allOf` to the child `anyOf`:

```
#!/usr/bin/env perl
use warnings;
use strict;
use JSON::Schema::AsType;
use Mojo::JSON 'decode_json';

my $json = do { local(@ARGV, $/) = 'schema/message.json';<> };
my $spec = decode_json($json);
my $schema = JSON::Schema::AsType->new( schema => $spec );

my $msg1 = { 
  event => 'PS',
  value => { phase => "Setup" },
  uuid  => '123456789',
  player => "1",
};
$schema->validate($msg1);
```

`Attribute (schema) does not pass the type constraint because: Validation failed for 'HashRef' with value BC`

**Comment by dnmfarrell** [comment]
Of course, my schema may well be wrong as well :)

**Comment by yanick** [comment]
Glad you're having fun with the module. :-)

And I think that your schema might indeed be wrong. Bear in mind, though, that I'm new to the JSON schema thingy. Buuuut I think that instead of 

```
{
      "properties": {
        "event": "BC",
        "value": {
          "$ref": "#/definitions/intersection"
        }
      },
```

it should be

```
{
      "properties": {
        "event": { "pattern": "^BC$" },
        "value": {
          "$ref": "#/definitions/intersection"
        }
      },
```

unless I  overlooked a special case that says that `"foo" : "bar"`  is a shortcut for `"foo": { enum: [ "bar"  ] }`, which is totally possible.

**Comment by dnmfarrell** [comment]
Gotcha! Sorry, my schema was littered with errors. Closing ... btw the [test script](https://github.com/dnmfarrell/Settlers-Game-Notation/blob/master/t/messages.t) correctly parses the schema and test data now.

**Comment by yanick** [comment]
Excellent! 

And I added `validate_schema` and `validate_explain_schema`, which will validate the schema itself against the draft3 or draft4 specs. Because it's schema validation all the way down, natch. :-)
