### ISSUE TITLE
Handle URIs with extra dots

### ISSUE THREAD

**Issue by dnmfarrell** [yanick/JSON-Schema-AsType#6]
The module fails to fetch certain URIs:
`couldn't get schema from 'https://raw.githubusercontent.com/dnmfarrell/Settlers-Game-Notation/master/schema/v0.3/message.json'`

I've swapped LWP::Simple for Mojo::UserAgent in my [fork](https://github.com/dnmfarrell/JSON-Schema-AsType/blob/releases/lib/JSON/Schema/AsType.pm) but you could use any other user agent I think. `HTTP::Tiny` works:

`perl -MHTTP::Tiny -wE 'say HTTP::Tiny->new->get("https://raw.githubusercontent.com/dnmfarrell/Settlers-Game-Notation/master/schema/v0.3/message.json")->{content}'`

It might be a the extra dot in the path `/v0.3/` ?

**Comment by dnmfarrell** [comment]
This works too, strangely:

`perl -MLWP::Simple -wE 'say LWP::Simple::get("https://raw.githubusercontent.com/dnmfarrell/Settlers-Game-Notation/master/schema/v0.3/message.json")'`

But this doesn't for me:

`perl -MJSON::Schema::AsType -e 'my $j = JSON::Schema::AsType->new(); $j->fetch("https://raw.githubusercontent.com/dnmfarrell/Settlers-Game-Notation/master/schema/v0.3/message.json")'
couldn't get schema from 'https://raw.githubusercontent.com/dnmfarrell/Settlers-Game-Notation/master/schema/v0.3/message.json'`

**Comment by dnmfarrell** [comment]
Ah I think I found the issue - the installed version of JSON::Schema::AsType wasn't working (IDKW), but after re-installing the latest GitHub build, it works fine. Bah!

**Comment by yanick** [comment]
I'm wondering, perhaps, if it's not a problem with redirections. The module does a straight-forward caching of the schemas it retrieves. It might have been puzzled by a 302. In all cases, poke me back if you see it again!
