### ISSUE TITLE
Deep Recursion (and not in the good way)

### ISSUE THREAD

**Issue by stevan** [yanick/JSON-Schema-AsType#8]
So I did this:
```
perl -MJSON::Schema::AsType -MData::Dumper=Dumper -E 'say Dumper( JSON::Schema::AsType->new( uri => "file://./swagger.json" )->validate_schema );'
```
and got this:
```
Deep recursion on subroutine "JSON::Schema::AsType::schema" at /Users/slittle/perl5/perlbrew/perls/perl-5.18.4/lib/site_perl/5.18.4/JSON/Schema/AsType.pm line 57.
Deep recursion on anonymous subroutine at reader JSON::Schema::AsType::schema (defined at /Users/slittle/perl5/perlbrew/perls/perl-5.18.4/lib/site_perl/5.18.4/MooseX/MungeHas.pm line 268) line 6.
Deep recursion on subroutine "JSON::Schema::AsType::fetch" at /Users/slittle/perl5/perlbrew/perls/perl-5.18.4/lib/site_perl/5.18.4/JSON/Schema/AsType.pm line 40.
^C
```
Upon further inspection I realized that if you do not have a schema, and only specify the URI, then [this code](https://github.com/yanick/JSON-Schema-AsType/blob/releases/lib/JSON/Schema/AsType.pm#L40)  calls [this code](https://github.com/yanick/JSON-Schema-AsType/blob/releases/lib/JSON/Schema/AsType.pm#L57) which results in it calling [this code](https://github.com/yanick/JSON-Schema-AsType/blob/releases/lib/JSON/Schema/AsType.pm#L40) which is gonna call [this code](https://github.com/yanick/JSON-Schema-AsType/blob/releases/lib/JSON/Schema/AsType.pm#L57) which is gonna then call [this code](https://github.com/yanick/JSON-Schema-AsType/blob/releases/lib/JSON/Schema/AsType.pm#L40), ... ah you get the picture.

**Comment by yanick** [comment]
Do'h!  Fix is  coming through.

Btw, LWP::Simple don't seem to like relative `file:///./blah/blah` urls, so you'll want to put an absolute path in there.

**Comment by yanick** [comment]
Or (for relative paths) you can do

```
use JSON::Schema::AsType;
use File::Serialize;

say "wee!" unless JSON::Schema::AsType->new( schema => deserialize_file 'message.json' )->validate_schema;
```

**Comment by mydimension** [comment]
I'm seeing similar deep recursion when validating a remote url:

```
$ perl -MJSON::Schema::AsType -MData::Dumper -E 'say Dumper(JSON::Schema::AsType->new(uri => "https://scap.nist.gov/schema/nvd/feed/0.1/nvd_cve_feed_json_0.1_beta.schema")->validate_schema)'
Deep recursion on subroutine "JSON::Schema::AsType::schema" at /Users/wcox/perl5/lib/perl5/JSON/Schema/AsType.pm line 88.
Deep recursion on anonymous subroutine at reader JSON::Schema::AsType::schema (defined at /Users/wcox/perl5/lib/perl5/MooseX/MungeHas.pm line 268) line 6.
```

it looks like the issue is around the `uri` being registered in the schema registry before the content is loaded and parsed.

**Comment by yanick** [comment]
@mydimension I think I fixed that in the branch `fetch-schema`. Can you try the module as it is on that branch and let me know if it works for you?

**Comment by mydimension** [comment]
yep, `fetch-schema` does indeed fix the recursion problem. thanks
